# -*- coding: utf-8 -*-
"""Detecção_de_emoção_Aula.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RkaiORCgpej23pW_OMq3X5w5iRrCEMb5
"""

#fazendo a importação das bibliotecas necessárias e a versão do CV2
import cv2
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import zipfile

cv2.__version__

# Commented out IPython magic to ensure Python compatibility.
#importando tensorflow
# %tensorflow_version 2.x
import tensorflow
tensorflow.__version__

#conexão com o Drive
from google.colab import drive
drive.mount('/content/gdrive')

#acessando a pasta Material.zip no Drive
path = "/content/gdrive/My Drive/Material.zip"
zip_object = zipfile.ZipFile(file=path, mode="r")
zip_object.extractall("./")

#descompactação da pasta
base_imgs = 'Material/fer2013.zip'
zip_object = zipfile.ZipFile(file = base_imgs, mode = 'r')
zip_object.extractall('./')
zip_object.close

data = pd.read_csv('fer2013/fer2013.csv')
data.tail() #mostra os últimos registros

plt.figure(figsize=(12,6))
plt.hist(data['emotion'], bins = 30) #7 divisoens de emoções
plt.title('Imagens x emoções')

#classes: ['Angry', 'Disgust ', 'Fear', 'Happy', 'Sad', 'Suprise', 'Neutral']

pixels = data['pixels'].tolist() #convertendo para lista
pixels

largura, altura = 48, 48 #dimensão das imagens
faces = [] #lista vazia
amostras = 0
for pixels_sequence in pixels:
  face = [int(pixel) for pixel in pixels_sequence.split(' ')] #conversão string para inteiro
  face = np.asarray(face).reshape(largura, altura)
  faces.append(face)

  if(amostras < 10):
    cv2_imshow(face)
  amostras += 1

print('Número total de imagens no dataset: ', str(len(faces)))

faces = np.asarray(faces)

faces.shape # quantidade de imagens, altura e largura

faces = np.expand_dims(faces, -1) # adicionar uma nova dimensão
faces.shape

def normalizar(x):
  x = x.astype('float32')
  x = x / 255.0
  return x

faces = normalizar(faces)

faces

emocoes = pd.get_dummies(data['emotion']).values

emocoes[0]

from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.losses import categorical_crossentropy
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.models import load_model
from tensorflow.keras.models import model_from_json

x_train, X_test, y_train, Y_test = train_test_split(faces, emocoes, test_size= 0.1, random_state = 42)
_, X_val, _, Y_val = train_test_split(x_train, y_train, test_size= 0.1, random_state = 41)

print('Número de imagens no conjunto de treinamento:', len(x_train))
print('Número de imagens no conjunto de teste:', len(X_test))
print('Número de imagens no conjunto de validação:', len(X_val))

from pandas._config.config import describe_option
num_features = 64
num_labels = 7 # classes
batch_size = 64 # quantos registros vai ser atualizado
epochs = 100 #execução por 100 epocas
width, height = 48, 48

model = Sequential()

model.add(Conv2D(num_features, kernel_size=(3,3), activation='relu',
                 input_shape=(width, height, 1), data_format = 'channels_last',
                 kernel_regularizer=l2(0.01)))
model.add(Conv2D(num_features, kernel_size=(3,3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(2*num_features, kernel_size=(3,3), activation='relu', padding = 'same')) #multiplicando o número de filtros
model.add(BatchNormalization())
model.add(Conv2D(2*num_features, kernel_size=(3,3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(2*2*num_features, kernel_size=(3,3), activation='relu', padding = 'same')) #multiplicando o número de filtros
model.add(BatchNormalization())
model.add(Conv2D(2*2*num_features, kernel_size=(3,3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))

model.add(Conv2D(2*2*2*num_features, kernel_size=(3,3), activation='relu', padding = 'same')) #multiplicando o número de filtros
model.add(BatchNormalization())
model.add(Conv2D(2*2*2*num_features, kernel_size=(3,3), activation='relu', padding='same'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))
model.add(Dropout(0.5))

model.add(Flatten())

model.add(Dense(2*2*2*num_features, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(2*2*num_features, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(2*num_features, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(num_labels, activation='softmax'))

model.summary()

model.compile(loss = 'categorical_crossentropy',
              optimizer = Adam(learning_rate = 0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-7), #paramentro beta é a taxa de decaimento expotencial
              metrics=['accuracy'])

arquivo_modelo = 'modelo_01_expressoes.h5'
arquivo_modelo_json = 'modelo_01_expressoes.json'

lr_reducar = ReduceLROnPlateau(monitor='val_loss', factor = 0.9, patience=3, verbose=1)
early_stopper = EarlyStopping(monitor='val_loss', min_delta = 0, patience=8, verbose=1, mode='auto') #faz parada antes das épocas definidas
checkpointer = ModelCheckpoint(arquivo_modelo, monitor='val_loss', verbose = 1, save_best_only = True)

model_json = model.to_json() # converte para format de texto json
with open(arquivo_modelo_json, 'w') as json_file:
  json_file.write(model_json) #grava a arquitetura

history = model.fit(np.array(x_train), np.array(y_train), # inicia o treinamento com os dados
                    batch_size = batch_size, #define o tamanho
                    epochs = epochs, #define o numero total
                    verbose = 1, #habilita a exibição detalhada
                    validation_data = (np.array(X_val), np.array(Y_val)), # tiliza os dados de validação
                    shuffle=True,
                    callbacks=[lr_reducar, early_stopper, checkpointer]) # ativa as funções de controle

print(history.history)

def plota_historico_modelo(historico_modelo): # define a função para gerar os gráficos
    fig, axs = plt.subplots(1, 2, figsize=(15,5)) # cria uma figura com subgráficos

    num_epochs = len(historico_modelo.history['accuracy'])
    tick_interval = max(1, num_epochs // 10) #calcula um intervalo

    axs[0].plot(range(1, num_epochs + 1), historico_modelo.history['accuracy'], 'r') #acurácia do treino
    axs[0].plot(range(1, num_epochs + 1), historico_modelo.history['val_accuracy'], 'b') #acurácia de validação
    axs[0].set_title('Acurácia do modelo')
    axs[0].set_ylabel('Acurácia')
    axs[0].set_xlabel('Epoch')
    axs[0].set_xticks(np.arange(1, num_epochs + 1, tick_interval)) #ajusta a escala com intervalo
    axs[0].legend(['training accuracy', 'validation_accuracy'], loc = 'best')

    axs[1].plot(range(1, num_epochs + 1), historico_modelo.history['loss'], 'r') # trein
    axs[1].plot(range(1, num_epochs + 1), historico_modelo.history['val_loss'], 'b') #validação
    axs[1].set_title('Perda do modelo')
    axs[1].set_ylabel('Perda')
    axs[1].set_xlabel('Epoch')
    axs[1].set_xticks(np.arange(1, num_epochs + 1, tick_interval)) #ajuste de escala
    axs[1].legend(['training loss', 'validation_loss'], loc = 'best')

plota_historico_modelo(history) #chama a função

#avalia o modelo usando os dados de teste, armazena os resultados
scores = model.evaluate(np.array(X_test), np.array(Y_test), batch_size = batch_size)

scores

print('Acurácia: ' + str(scores[1]))
print('Erro: ' + str(scores[0]))

true_y = [] # lista vazia para valores reais
pred_y = [] # lista vazia para previsões
x = X_test # carrega os dados de teste
y = Y_test # carrega os rótulos de teste

x[0] # acessa o primeiro elemento

y[0]

json_file = open(arquivo_modelo_json, 'r') #abre o arquivo do modelo para ler
loaded_model_json = json_file.read() #lê o conteúdo do arquivo json
json_file.close() #fecha o arquivo

loaded_model = model_from_json(loaded_model_json)
loaded_model.load_weights(arquivo_modelo) #carrega os pesos

y_pred = loaded_model.predict(x) #realiza as previsõe

y_pred[0] #acessa as probabilidades da primeira previsão

yp = y_pred.tolist() # converte o array para uma lista
yt = y.tolist() # converte o array de valores para uma lista
count = 0

len(y) # verifica o tamanho total do array

for i in range(len(y)): # inicia um loop
    yy = max(yp[i]) # encontra o valor máximo na lista
    yyt = max(yt[i]) # encontra o valor máximo na lista

for i in range(len(y)): # inicia o loop
    yy = max(yp[i]) # pega o maior valor
    yyt = max(yt[i]) # pega o maior valor real
    pred_y.append(yp[i].index(yy)) # adiciona o índice da classe
    true_y.append(yt[i].index(yyt)) # adiciona o índice da classe real na lista
    if (yp[i].index(yy) == yt[i].index(yyt)): # verifica se a previsão acertou o real
        count += 1

acc = (count / len(y)) * 100 # calcula a porcentagem de acurácia

print('Acurácia no conjunto de teste: ' + str(acc))

np.save('truey_mod01', true_y) # salva os rótulos reais
np.save('predy_mod01', pred_y) # salva as previsões do modelo

from sklearn.metrics import confusion_matrix # importa a função para criar a matriz

y_true = np.load('truey_mod01.npy') # carrega os valores salvas
y_pred = np.load('predy_mod01.npy') # carrega as previsões salvas

cm = confusion_matrix(y_true, y_pred) # calcula a matriz de confusão
expressoes = ['Raiva', 'Nojo', 'Medo', 'Feliz', 'Triste', 'Surpreso', 'Neutro'] # define as emoções
titulo = 'Matriz de Confusão'
print(cm)

import itertools # importa ferramenta para iterar matriz
plt.imshow(cm, interpolation='nearest', cmap=plt.cm.Blues) # renderiza a matriz
plt.title(titulo) # adiciona o título
plt.colorbar() # adiciona a barra lateral
tick_marks = np.arange(len(expressoes)) # define as posições das marcações
plt.xticks(tick_marks, expressoes, rotation=45) # define nomes e rotaciona
plt.yticks(tick_marks, expressoes) # define os nomes das legendas
fmt = 'd' # define formato de números
thresh = cm.max() / 2. # calcula limiar

for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])): # percorre cada célula
    plt.text(j, i, format(cm[i, j], fmt), horizontalalignment='center', color='white' if cm[i,j] > thresh else 'black')

plt.ylabel('Classificação correta')
plt.xlabel('Predição')
plt.savefig('matriz_confusao_mod01.png')

imagem = cv2.imread('Material/testes/teste02.jpg')
cv2_imshow(imagem)

original = imagem.copy()
gray = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
cv2_imshow(gray)

faces

